version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=<PUID>
      - PGID=<PGID>
      - TZ=Asia/Kolkata
      - JELLYFIN_PublishedServerUrl=<Enter URL> #optional
    volumes:
      - /home/ubuntu/docker_apps/jellyfin/config/:/config
      - /home/ubuntu/data/media/:/data/media
    #ports:
    #  - 8096:8096
    #  - 8920:8920 #optional
    #  - 7359:7359/udp #optional
    #  - 1900:1900/udp #optional
    restart: unless-stopped